export enum Categories {
  SALARY = "SALÁRIO",
  RENT = "ALUGUEL",
  FOOD = "ALIMENTAÇÃO",
  TRANSPORTATION = "TRANSPORTE",
  ENTERTAINMENT = "LAZER",
  EDUCATION = "EDUCAÇÃO",
  HEALTH = "SAÚDE",
  OTHERS = "OUTROS",
}
